// Frozen production data for the landing page's "recorded build" hero animation
// (Tasks 17-18). Generated by scripts/export-recorded-build.ts, read-only against
// production Postgres. Every number here traces back to one real run's trace_json.
//
// Source: slug "mintlify" (mintlify.com)
// Generation run: 7afb8bd2-86ff-4b75-917e-ffcc417751bd
// Exported: 2026-08-02
//
// Plain data, no imports: this feeds a client component and must stay inert.

export interface RecordedBuild {
  domain: string;
  companyName: string;
  oneLiner: string;
  filedDate: string;
  clippings: Array<{ source: string; date: string; headline: string }>; // up to 4, from the card's citations/signals
  events: string[]; // ordered stage lines derived from the real trace
  counts: { documentsOpened: number; documentsKept: number; factsKept: number };
  sections: { money: string[]; people: string[]; signals: string[]; sources: string[] };
  lens?: { whyCare: string; whatMustBeTrue: string }; // present only when the card carries synthesis
}

export const recordedBuild: RecordedBuild = {
  "domain": "mintlify.com",
  "companyName": "Mintlify",
  "oneLiner": "Mintlify sells documentation and knowledge infrastructure to software companies, letting developers publish and maintain structured docs that serve both human readers and AI agents consuming product knowledge.",
  "filedDate": "2026-05-15",
  "clippings": [
    {
      "source": "mintlify.com",
      "date": "2026-05-15",
      "headline": "Customers - Mintlify"
    },
    {
      "source": "mintlify.com",
      "date": "2026-05-01",
      "headline": "Introducing the Mintlify Help Center Starter Kit"
    },
    {
      "source": "mintlify.com",
      "date": "2026-04-29",
      "headline": "Workflows, rebuilt"
    },
    {
      "source": "dailycompanynews.com",
      "date": "2026-04-20",
      "headline": "Mintlify announces MCP support and AI-agent-native doc workflows alongside Series B"
    }
  ],
  "events": [
    "Reading mintlify.com",
    "Opened 55 documents, kept 49",
    "Cut 35 facts, each pinned to a document",
    "Filed"
  ],
  "counts": {
    "documentsOpened": 55,
    "documentsKept": 49,
    "factsKept": 35
  },
  "sections": {
    "money": [
      "Raised $67M across disclosed rounds.",
      "Series B closed Apr 2026, led by Andreessen Horowitz."
    ],
    "people": [
      "Han Wang",
      "Hahnbee Lee",
      "Nicholas Khami"
    ],
    "signals": [
      "Customers - Mintlify",
      "Introducing the Mintlify Help Center Starter Kit",
      "Workflows, rebuilt",
      "Mintlify announces MCP support and AI-agent-native doc workflows alongside Series B",
      "Mintlify raises $45M Series B led by a16z and Salesforce Ventures at $500M valuation",
      "Ruairi Wiepking joins as Head of Sales (April 2026), signaling enterprise GTM build-out post-Series B"
    ],
    "sources": [
      "mintlify.com",
      "builtinsf.com",
      "dailyaibrief.com",
      "a16z.com",
      "menlotimes.com",
      "dailycompanynews.com",
      "futureteknow.com",
      "vctavern.com",
      "landing.mintlify.com"
    ]
  },
  "lens": {
    "whyCare": "Mintlify sits at the intersection of two compounding shifts—AI agents increasingly consuming documentation programmatically and software teams needing infrastructure that serves both human and machine readers—making its platform a potential toll-road for how products are understood and used by AI systems at scale.",
    "whatMustBeTrue": "Remarkable scale and velocity for a 2022 founding: 20,000+ companies, 100M+ annual users, and a $500M Series B valuation roughly 18 months after an $18M Series A—suggesting strong product-market fit and efficient top-of-funnel growth."
  }
};
